apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  ports:
  - name: apache-http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31001
  selector:
    app: apache
  type: NodePort
