apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: apache
    spec:      
      containers:
      - name: apache
        image: thecloudgarage/k8s-springboot-kafka-order-management:mskafka_apache
        ports:
        - name: apache-http
          containerPort: 80
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5        
        readinessProbe:
          httpGet:
             path: /index.html
             port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
