apiVersion: v1
kind: Service
metadata:
  name: invoicing
  labels:
    app: invoicing
spec:
  ports:
  - name: invoicing-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: invoicing
