apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  ports:
  - name: shipping-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: shipping
