apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      nodePort: 31003
  selector:
    app: postgresql
  type: NodePort   
