version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
  apache:
    build: apache
    links:
     - order
     - shipping
     - invoicing
    ports:
     - "8080:80"
  postgresql:
    build: postgres
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
  order:
    build: ../microservice-kafka/microservice-kafka-order
    links:
     - kafka
     - postgresql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      postgresql: postgresql
  shipping:
    build: ../microservice-kafka/microservice-kafka-shipping
    links:
     - kafka
     - postgresql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      postgresql: postgresql
  invoicing:
    build: ../microservice-kafka/microservice-kafka-invoicing
    links:
     - kafka
     - postgresql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      postgresql: postgresql

